import type { NextPage } from 'next'
import Head from 'next/head'
import { SyntheticEvent, useContext, useState, ChangeEvent } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';

import withAuth from '../hocs/withAuth';


import Button from '@mui/material/Button';

const Home: NextPage = () => {
  const homePage = async (e: SyntheticEvent) => {
    try {
      const response = await axios.get('/test')

      console.log('data: ', response.data);
      // await router.push('/');
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div>
      <Head>
        <title>Together</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home Page</h1>
      <Button variant="contained" color="success">success</Button>
      <Button variant="outlined" onClick={homePage}>
        HomePage
      </Button>
    </div>
  )
}

// export function getServerSideProps() {
//   // const AuthContextz = useContext(AuthContext);
//   // console.log("AuthContext: ", AuthContextz)
//   const isLogin = !!Cookies.get('token');
//   console.log("islogin: ", isLogin)
//   if (!isLogin)
//     return {
//       // redirect: {
//       //   destination: '/login',
//       //   permanent: false,
//       // },
//     };

//   return {
//     props: {},
//   };
// }

export default withAuth(Home)
